import { Orbitron } from 'next/font/google';
import './globals.css';

const inter = Orbitron({ subsets: ['latin'], weight: ['400'] });

export const metadata = {
  title: 'Games',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`bg-gray-900 ${inter.className}`}>{children}</body>
    </html>
  );
}
